run-ges-tests:
  stage: test
  image: registry.freedesktop.org/thiblahute/gstreamer/amd64/fedora:2025-03-14.0-1.26
  tags: ["gstreamer"]

  variables:
    RUSTUP_HOME: usr/local/rustup"
    CARGO_HOME: usr/local/cargo"
    GI_SCANNER_DISABLE_CACHE: "1"
    TIMEOUT_FACTOR: "2"
    PYTHONFAULTHANDLER: "enabled"

  script:
    - mkdir -p ~/.config/gdb
    - echo "set auto-load safe-path /" >> ~/.config/gdb/gdbinit
    - export PATH="/usr/local/cargo/bin:$PATH"
    - meson subprojects update --reset
    - meson setup --native-file ci/docker/tella/native.ini -Dpackage-origin="Sequence $(git rev-parse --short HEAD)" builddir
    - ninja -C builddir
    - git config --global --add safe.directory $PWD
    - GES_ENABLE_URIDECODEPOOLSRC=true ./gst-env.py gst-validate-launcher ges --dump-on-failure -j 5 --sync -b "ges.test.*" -b ".*title.*"

  artifacts:
    expire_in: "14 days"
    when: always
    paths:
      - "meson-logs/"
      - "$CI_PROJECT_DIR/validate-logs"
    reports:
      junit:
        - "$CI_PROJECT_DIR/validate-logs/*.xml"
